### ISSUE TITLE
Hardcoded constant for `tokenURI`

### ISSUE THREAD

**Issue by h0tw4t3r** [curraprotocol/contracts#1]
https://github.com/curraprotocol/contracts/blob/3b8a1d8a89779d5abf1df548913989f938e776a4/src/Curra.sol#L56

Use `_baseURI` overriding here. And expose `setBaseURI` method for `onlyOwner`.

**Comment by poloplayingsolo** [comment]
Make sense, added to plan

**Comment by poloplayingsolo** [comment]
fixed and released
