### ISSUE TITLE
Possible Optimization

### ISSUE THREAD

**Issue by h0tw4t3r** [curraprotocol/contracts#2]
Can those be composed in one call? To set implementation straight on proxy construction? - CALL

https://github.com/curraprotocol/contracts/blob/3b8a1d8a89779d5abf1df548913989f938e776a4/src/Curra.sol#L79-L80

**Comment by poloplayingsolo** [comment]
it's not possible
https://github.com/curraprotocol/contracts/blob/4c0736995fc0a006e95c89f32d345c890d4aaf37/src/Curra.sol#LL71C22-L71C39

**Comment by poloplayingsolo** [comment]
It's not possible, look how the proxy address is precalculated:
https://github.com/curraprotocol/contracts/blob/4c0736995fc0a006e95c89f32d345c890d4aaf37/src/Curra.sol#L71
This address is going to be used to deploy `Forwarder` here:
https://github.com/curraprotocol/contracts/blob/4c0736995fc0a006e95c89f32d345c890d4aaf37/src/Curra.sol#L75
The main problem is that proxy implementation `WhitelistedAddressRule` depends on `Forwarder` address, which depends on `Proxy` address. We can't know `WhitelistedAddressRule` address at the proxy address precalculation step to include it in init code

**Comment by h0tw4t3r** [comment]
> It's not possible, look how the proxy address is precalculated:
> 
> https://github.com/curraprotocol/contracts/blob/4c0736995fc0a006e95c89f32d345c890d4aaf37/src/Curra.sol#L71
> 
> 
> This address is going to be used to deploy `Forwarder` here:
> https://github.com/curraprotocol/contracts/blob/4c0736995fc0a006e95c89f32d345c890d4aaf37/src/Curra.sol#L75
> 
> 
> The main problem is that proxy implementation `WhitelistedAddressRule` depends on `Forwarder` address, which depends on `Proxy` address. We can't know `WhitelistedAddressRule` address at the proxy address precalculation step to include it in init code

Hmm, I understand. Sort of a chicken-and-egg problem.

Decomposing anything in the third-party object would increase runtime gas costs, thus it's the best way to do it.
