### ISSUE TITLE
`LightProxy` to use immutables

### ISSUE THREAD

**Issue by h0tw4t3r** [curraprotocol/contracts#3]
https://github.com/curraprotocol/contracts/blob/3b8a1d8a89779d5abf1df548913989f938e776a4/src/LightProxy.sol#L16-L17

Why don't use `immutable` here?

**Comment by poloplayingsolo** [comment]
Some extra hassle is required to get the init code of the contract with immutable variables here:
https://github.com/curraprotocol/contracts/blob/4c0736995fc0a006e95c89f32d345c890d4aaf37/src/Curra.sol#LL71C12-L71C12
Can't find an easier way to achieve that without precompiling the contract off-chain and copying bytecode into literal. This operation will be rarely used, so I decided to skip this step

**Comment by h0tw4t3r** [comment]
Ok, makes sense
