### ISSUE TITLE
Obsolete check if moved to `LightProxy` constructor.

### ISSUE THREAD

**Issue by h0tw4t3r** [curraprotocol/contracts#4]
https://github.com/curraprotocol/contracts/blob/3b8a1d8a89779d5abf1df548913989f938e776a4/src/LightProxy.sol#L35

**Comment by poloplayingsolo** [comment]
looks like dup of https://github.com/curraprotocol/contracts/issues/2?

**Comment by h0tw4t3r** [comment]
Yes and no. This should be **normally** fixed within PR that implements #2.

**Comment by h0tw4t3r** [comment]
@poloplayingsolo, are OR conditions checked RTL or LTR? I'm not sure whether the shortest branch is chosen when checking this.

**Comment by poloplayingsolo** [comment]
fixed after moved to solady's proxies
