### ISSUE TITLE
`op` could be `uint8`

### ISSUE THREAD

**Issue by h0tw4t3r** [curraprotocol/contracts#5]
There are exactly `8` operations.

https://github.com/curraprotocol/contracts/blob/3b8a1d8a89779d5abf1df548913989f938e776a4/src/RuleBase.sol#L209

**Comment by poloplayingsolo** [comment]
_uint8_ 15 batches test: **564563** gas
_uint256_ 15 batches test: **564563** gas
gas usage not impacted, but uint8 makes code more readable, changed in 4c0736995fc0a006e95c89f32d345c890d4aaf37, thank you!
